# Generated by Django 5.2.8 on 2025-12-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_files', '0004_delete_google_job_hire'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=250)),
                ('job_name', models.CharField(max_length=150)),
                ('Location', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=15000)),
                ('Industry', models.CharField(max_length=150)),
                ('Company_Size', models.CharField(max_length=150)),
                ('Experience', models.CharField(max_length=150)),
                ('Skills', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=15000)),
                ('Website', models.CharField(max_length=150)),
                ('google_login_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
    ]
