# Generated by Django 5.2.8 on 2025-12-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_files', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_list',
        ),
    ]
