# Generated by Django 5.2.8 on 2025-12-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0005_alter_employee_profile_image'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='google_login_reference',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
            preserve_default=False,
        ),
    ]
