# Generated by Django 5.2.8 on 2025-12-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0007_alter_job_list_google_login_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_list',
        ),
    ]
