# Generated by Django 5.2.8 on 2025-12-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0008_delete_job_list'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=250, null=True)),
                ('job_name', models.CharField(max_length=150, null=True)),
                ('Location', models.CharField(max_length=500, null=True)),
                ('Type', models.CharField(max_length=150, null=True)),
                ('content', models.TextField(null=True)),
                ('Industry', models.CharField(max_length=150, null=True)),
                ('Company_Size', models.CharField(max_length=150, null=True)),
                ('Experience', models.CharField(max_length=150, null=True)),
                ('Skills', models.CharField(max_length=150, null=True)),
                ('Description', models.TextField(null=True)),
                ('Website', models.CharField(max_length=150, null=True)),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='socialaccount.socialaccount')),
            ],
        ),
    ]
