# Generated by Django 5.2.8 on 2025-12-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0009_job_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_list',
            name='google_account',
        ),
        migrations.AlterField(
            model_name='job_list',
            name='Description',
            field=models.CharField(max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='job_list',
            name='content',
            field=models.CharField(max_length=15000, null=True),
        ),
    ]
