# Generated by Django 5.2.8 on 2025-12-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0011_job_list_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='education',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='project',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='work_experience',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
